import Foundation
import StoryboardCore

/// The TypeScript declarations and editor config written beside a script.
///
/// **Everything here is derived from the tables the engine installs.** That is
/// the whole design, and it is not caution for its own sake: the hand-written
/// version of this already shipped. The completion table carried all
/// thirty-five easing names backwards — `outQuad` where the enum says
/// `quadOut` — so a name the runtime rejects arrived as `undefined`, became
/// NaN, was clamped to zero, and zero is `linear`. A script animated
/// differently from what was asked, in silence, in a saved project.
///
/// A generated file cannot disagree with the runtime, because there is only
/// one list. Adding an easing, an image or a sprite method reaches the editor
/// with no work here at all.
public enum TypeDeclarations {
    /// What the declarations file is called.
    ///
    /// Taken from `ScriptStore` rather than declared again: the watcher has to
    /// recognise these names without depending on this target, and two
    /// spellings of one file name is how a watcher starts reacting to our own
    /// writes.
    public static let fileName = ScriptStore.declarationsFileName

    /// What the editor config is called.
    public static let configurationFileName = ScriptStore.configurationFileName

    /// The declarations, as one file.
    public static var text: String {
        """
        // Generated by Animate Editor. Do not edit.
        //
        // Every name below is derived from what the script engine installs, so
        // this file cannot offer you something the runtime would reject. Edit
        // the app, not this file — the next time a project opens, whatever you
        // wrote here is replaced.

        \(spriteBuilder)

        \(easeBlock)

        \(imageBlock)

        \(layerBlock)

        \(originBlock)

        \(globals)
        """
    }

    /// The config that makes an editor read the declarations at all.
    ///
    /// Measured, not assumed: with a `.d.ts` alone the declarations are
    /// **silently ignored** while autocompletion still appears to work,
    /// offering identifiers scraped from the file's own text — the failure that
    /// looks exactly like success. With this file, a misspelled easing and a
    /// wrong argument count are both flagged as you type.
    public static var configuration: String {
        """
        {
          "//": "Generated by Animate Editor. Do not edit.",
          "compilerOptions": {
            "checkJs": true,
            "noEmit": true,
            "target": "es2020",
            "//lib": "No 'dom': our Image would resolve to HTMLImageElement.",
            "lib": ["es2020"],
            "//moduleDetection": "Each script is its own scope. Without this every script in the folder shares one global scope, so a second clip declaring `count` is flagged as redeclaring the first one's — an error about code in another file the author is not editing.",
            "moduleDetection": "force",
            "module": "esnext"
          },
          "include": ["*.js", "\(fileName)"]
        }

        """
    }

    // MARK: - Derived pieces

    /// The builder interface, one method per `SpriteMethod`.
    private static var spriteBuilder: String {
        let methods = SpriteMethod.allCases.flatMap { method -> [String] in
            let values = (0 ..< method.valueCount).map { "value\($0 + 1): number" }
            guard method.isTimed else {
                return ["  \(method.rawValue)(\(values.joined(separator: ", "))): SpriteBuilder"]
            }

            // Two overloads, not one optional-first parameter.
            //
            // The easing may be omitted and it comes **first**, which is why
            // the bridge reads arguments by count. Declared as
            // `easing?: number` ahead of required parameters, TypeScript
            // rejects every correct call — measured: a valid `.move(Ease.…, 0,
            // 900, 320, 240, 400, 300)` was flagged "Expected 5 arguments, but
            // got 4", because an optional cannot precede required ones. Two
            // signatures say the same thing and accept both spellings.
            let timing = ["startTime: number", "endTime: number"]
            return [
                "  \(method.rawValue)(\((timing + values).joined(separator: ", "))): SpriteBuilder",
                "  \(method.rawValue)(\((["easing: number"] + timing + values).joined(separator: ", "))): SpriteBuilder",
            ]
        }

        return """
        /** A sprite being built. Every method returns it, so calls chain. */
        declare interface SpriteBuilder {
        \(methods.joined(separator: "\n"))
        }
        """
    }

    private static var easeBlock: String {
        block(
            named: "Ease",
            summary: "The easing curves, by the names osu! gives them.",
            entries: EaseConstants.table.map { ($0.key, "\($0.value)") },
        )
    }

    private static var imageBlock: String {
        block(
            named: "Image",
            summary: "The images the app provides. A path relative to the beatmap folder also works.",
            entries: ImageConstants.table.map { ($0.key, "string") },
        )
    }

    private static var layerBlock: String {
        block(
            named: "Layer",
            summary: "The storyboard layers.",
            entries: LayerConstants.table.map { ($0.key, "string") },
        )
    }

    private static var originBlock: String {
        block(
            named: "Origin",
            summary: "Where a sprite's position sits inside its image.",
            entries: LayerConstants.originTable.map { ($0.key, "string") },
        )
    }

    /// The free functions and values.
    ///
    /// `params` and `param` are typed loosely on purpose: a script declares its
    /// own controls, so their names are not knowable here — and a signature
    /// that pretended otherwise would flag valid code.
    private static var globals: String {
        """
        /** Creates a sprite. `image` is an `Image` value or a path in the beatmap folder. */
        declare function sprite(
            image: string,
            options?: { layer?: string; origin?: string },
        ): SpriteBuilder

        /** How long this clip runs, in milliseconds. Local time: a clip starts at 0. */
        declare const duration: number

        /** Declares the controls the inspector draws for this script. */
        declare function params(declarations: Record<string, {
            type: 'number' | 'integer' | 'boolean' | 'color' | 'choice'
            default?: number | boolean | string
            range?: [number, number]
            unit?: string
            choices?: string[]
        }>): void

        /** Reads a control declared by `params`. */
        declare function param(name: string): any

        /** A seeded random number in [0, 1). Deterministic, so the preview matches the export. */
        declare function rng(): number

        declare const console: { log(...values: any[]): void }
        """
    }

    /// One `declare const` block, sorted so regeneration is byte-identical.
    ///
    /// Sorting matters: the tables are dictionaries, whose order is not stable
    /// between runs. An unsorted block would rewrite the file with the same
    /// content in a different order on every project open — a diff nobody can
    /// read, in a file that lands in someone's version control.
    private static func block(
        named name: String,
        summary: String,
        entries: [(String, String)],
    ) -> String {
        let lines = entries
            .sorted { $0.0 < $1.0 }
            .map { "  readonly \($0.0): \($0.1)" }

        return """
        /** \(summary) */
        declare const \(name): {
        \(lines.joined(separator: "\n"))
        }
        """
    }
}
