
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T


export const EditorMonacoEditor: typeof import("../app/components/editor/MonacoEditor.vue")['default']
export const EditorPreviewCanvas: typeof import("../app/components/editor/PreviewCanvas.vue")['default']
export const EditorTimeline: typeof import("../app/components/editor/Timeline.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtTime: typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const Accordion: typeof import("../app/components/ui/accordion/index")['Accordion']
export const AccordionContent: typeof import("../app/components/ui/accordion/index")['AccordionContent']
export const AccordionItem: typeof import("../app/components/ui/accordion/index")['AccordionItem']
export const AccordionTrigger: typeof import("../app/components/ui/accordion/index")['AccordionTrigger']
export const Alert: typeof import("../app/components/ui/alert/index")['Alert']
export const AlertDescription: typeof import("../app/components/ui/alert/index")['AlertDescription']
export const AlertTitle: typeof import("../app/components/ui/alert/index")['AlertTitle']
export const AlertDialog: typeof import("../app/components/ui/alert-dialog/index")['AlertDialog']
export const AlertDialogAction: typeof import("../app/components/ui/alert-dialog/index")['AlertDialogAction']
export const AlertDialogCancel: typeof import("../app/components/ui/alert-dialog/index")['AlertDialogCancel']
export const AlertDialogContent: typeof import("../app/components/ui/alert-dialog/index")['AlertDialogContent']
export const AlertDialogDescription: typeof import("../app/components/ui/alert-dialog/index")['AlertDialogDescription']
export const AlertDialogFooter: typeof import("../app/components/ui/alert-dialog/index")['AlertDialogFooter']
export const AlertDialogHeader: typeof import("../app/components/ui/alert-dialog/index")['AlertDialogHeader']
export const AlertDialogTitle: typeof import("../app/components/ui/alert-dialog/index")['AlertDialogTitle']
export const AlertDialogTrigger: typeof import("../app/components/ui/alert-dialog/index")['AlertDialogTrigger']
export const Avatar: typeof import("../app/components/ui/avatar/index")['Avatar']
export const AvatarFallback: typeof import("../app/components/ui/avatar/index")['AvatarFallback']
export const AvatarImage: typeof import("../app/components/ui/avatar/index")['AvatarImage']
export const Badge: typeof import("../app/components/ui/badge/index")['Badge']
export const Breadcrumb: typeof import("../app/components/ui/breadcrumb/index")['Breadcrumb']
export const BreadcrumbEllipsis: typeof import("../app/components/ui/breadcrumb/index")['BreadcrumbEllipsis']
export const BreadcrumbItem: typeof import("../app/components/ui/breadcrumb/index")['BreadcrumbItem']
export const BreadcrumbLink: typeof import("../app/components/ui/breadcrumb/index")['BreadcrumbLink']
export const BreadcrumbList: typeof import("../app/components/ui/breadcrumb/index")['BreadcrumbList']
export const BreadcrumbPage: typeof import("../app/components/ui/breadcrumb/index")['BreadcrumbPage']
export const BreadcrumbSeparator: typeof import("../app/components/ui/breadcrumb/index")['BreadcrumbSeparator']
export const Button: typeof import("../app/components/ui/button/index")['Button']
export const Calendar: typeof import("../app/components/ui/calendar/index")['Calendar']
export const CalendarCell: typeof import("../app/components/ui/calendar/index")['CalendarCell']
export const CalendarCellTrigger: typeof import("../app/components/ui/calendar/index")['CalendarCellTrigger']
export const CalendarGrid: typeof import("../app/components/ui/calendar/index")['CalendarGrid']
export const CalendarGridBody: typeof import("../app/components/ui/calendar/index")['CalendarGridBody']
export const CalendarGridHead: typeof import("../app/components/ui/calendar/index")['CalendarGridHead']
export const CalendarGridRow: typeof import("../app/components/ui/calendar/index")['CalendarGridRow']
export const CalendarHeadCell: typeof import("../app/components/ui/calendar/index")['CalendarHeadCell']
export const CalendarHeader: typeof import("../app/components/ui/calendar/index")['CalendarHeader']
export const CalendarHeading: typeof import("../app/components/ui/calendar/index")['CalendarHeading']
export const CalendarNextButton: typeof import("../app/components/ui/calendar/index")['CalendarNextButton']
export const CalendarPrevButton: typeof import("../app/components/ui/calendar/index")['CalendarPrevButton']
export const ButtonGroup: typeof import("../app/components/ui/button-group/index")['ButtonGroup']
export const ButtonGroupSeparator: typeof import("../app/components/ui/button-group/index")['ButtonGroupSeparator']
export const ButtonGroupText: typeof import("../app/components/ui/button-group/index")['ButtonGroupText']
export const ChartContainer: typeof import("../app/components/ui/chart/index")['ChartContainer']
export const ChartLegendContent: typeof import("../app/components/ui/chart/index")['ChartLegendContent']
export const ChartTooltipContent: typeof import("../app/components/ui/chart/index")['ChartTooltipContent']
export const ChartCrosshair: typeof import("../app/components/ui/chart/index")['ChartCrosshair']
export const ChartTooltip: typeof import("../app/components/ui/chart/index")['ChartTooltip']
export const Carousel: typeof import("../app/components/ui/carousel/index")['Carousel']
export const CarouselContent: typeof import("../app/components/ui/carousel/index")['CarouselContent']
export const CarouselItem: typeof import("../app/components/ui/carousel/index")['CarouselItem']
export const CarouselNext: typeof import("../app/components/ui/carousel/index")['CarouselNext']
export const CarouselPrevious: typeof import("../app/components/ui/carousel/index")['CarouselPrevious']
export const CarouselApi: typeof import("../app/components/ui/carousel/index")['CarouselApi']
export const AspectRatio: typeof import("../app/components/ui/aspect-ratio/index")['AspectRatio']
export const Card: typeof import("../app/components/ui/card/index")['Card']
export const CardAction: typeof import("../app/components/ui/card/index")['CardAction']
export const CardContent: typeof import("../app/components/ui/card/index")['CardContent']
export const CardDescription: typeof import("../app/components/ui/card/index")['CardDescription']
export const CardFooter: typeof import("../app/components/ui/card/index")['CardFooter']
export const CardHeader: typeof import("../app/components/ui/card/index")['CardHeader']
export const CardTitle: typeof import("../app/components/ui/card/index")['CardTitle']
export const Collapsible: typeof import("../app/components/ui/collapsible/index")['Collapsible']
export const CollapsibleContent: typeof import("../app/components/ui/collapsible/index")['CollapsibleContent']
export const CollapsibleTrigger: typeof import("../app/components/ui/collapsible/index")['CollapsibleTrigger']
export const Checkbox: typeof import("../app/components/ui/checkbox/index")['Checkbox']
export const Dialog: typeof import("../app/components/ui/dialog/index")['Dialog']
export const DialogClose: typeof import("../app/components/ui/dialog/index")['DialogClose']
export const DialogContent: typeof import("../app/components/ui/dialog/index")['DialogContent']
export const DialogDescription: typeof import("../app/components/ui/dialog/index")['DialogDescription']
export const DialogFooter: typeof import("../app/components/ui/dialog/index")['DialogFooter']
export const DialogHeader: typeof import("../app/components/ui/dialog/index")['DialogHeader']
export const DialogOverlay: typeof import("../app/components/ui/dialog/index")['DialogOverlay']
export const DialogScrollContent: typeof import("../app/components/ui/dialog/index")['DialogScrollContent']
export const DialogTitle: typeof import("../app/components/ui/dialog/index")['DialogTitle']
export const DialogTrigger: typeof import("../app/components/ui/dialog/index")['DialogTrigger']
export const ContextMenu: typeof import("../app/components/ui/context-menu/index")['ContextMenu']
export const ContextMenuCheckboxItem: typeof import("../app/components/ui/context-menu/index")['ContextMenuCheckboxItem']
export const ContextMenuContent: typeof import("../app/components/ui/context-menu/index")['ContextMenuContent']
export const ContextMenuGroup: typeof import("../app/components/ui/context-menu/index")['ContextMenuGroup']
export const ContextMenuItem: typeof import("../app/components/ui/context-menu/index")['ContextMenuItem']
export const ContextMenuLabel: typeof import("../app/components/ui/context-menu/index")['ContextMenuLabel']
export const ContextMenuRadioGroup: typeof import("../app/components/ui/context-menu/index")['ContextMenuRadioGroup']
export const ContextMenuRadioItem: typeof import("../app/components/ui/context-menu/index")['ContextMenuRadioItem']
export const ContextMenuSeparator: typeof import("../app/components/ui/context-menu/index")['ContextMenuSeparator']
export const ContextMenuShortcut: typeof import("../app/components/ui/context-menu/index")['ContextMenuShortcut']
export const ContextMenuSub: typeof import("../app/components/ui/context-menu/index")['ContextMenuSub']
export const ContextMenuSubContent: typeof import("../app/components/ui/context-menu/index")['ContextMenuSubContent']
export const ContextMenuSubTrigger: typeof import("../app/components/ui/context-menu/index")['ContextMenuSubTrigger']
export const ContextMenuTrigger: typeof import("../app/components/ui/context-menu/index")['ContextMenuTrigger']
export const Command: typeof import("../app/components/ui/command/index")['Command']
export const CommandDialog: typeof import("../app/components/ui/command/index")['CommandDialog']
export const CommandEmpty: typeof import("../app/components/ui/command/index")['CommandEmpty']
export const CommandGroup: typeof import("../app/components/ui/command/index")['CommandGroup']
export const CommandInput: typeof import("../app/components/ui/command/index")['CommandInput']
export const CommandItem: typeof import("../app/components/ui/command/index")['CommandItem']
export const CommandList: typeof import("../app/components/ui/command/index")['CommandList']
export const CommandSeparator: typeof import("../app/components/ui/command/index")['CommandSeparator']
export const CommandShortcut: typeof import("../app/components/ui/command/index")['CommandShortcut']
export const Combobox: typeof import("../app/components/ui/combobox/index")['Combobox']
export const ComboboxAnchor: typeof import("../app/components/ui/combobox/index")['ComboboxAnchor']
export const ComboboxEmpty: typeof import("../app/components/ui/combobox/index")['ComboboxEmpty']
export const ComboboxGroup: typeof import("../app/components/ui/combobox/index")['ComboboxGroup']
export const ComboboxInput: typeof import("../app/components/ui/combobox/index")['ComboboxInput']
export const ComboboxItem: typeof import("../app/components/ui/combobox/index")['ComboboxItem']
export const ComboboxItemIndicator: typeof import("../app/components/ui/combobox/index")['ComboboxItemIndicator']
export const ComboboxList: typeof import("../app/components/ui/combobox/index")['ComboboxList']
export const ComboboxSeparator: typeof import("../app/components/ui/combobox/index")['ComboboxSeparator']
export const ComboboxViewport: typeof import("../app/components/ui/combobox/index")['ComboboxViewport']
export const ComboboxCancel: typeof import("../app/components/ui/combobox/index")['ComboboxCancel']
export const ComboboxTrigger: typeof import("../app/components/ui/combobox/index")['ComboboxTrigger']
export const DropdownMenu: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenu']
export const DropdownMenuCheckboxItem: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuCheckboxItem']
export const DropdownMenuContent: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuContent']
export const DropdownMenuGroup: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuGroup']
export const DropdownMenuItem: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuItem']
export const DropdownMenuLabel: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuLabel']
export const DropdownMenuRadioGroup: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuRadioGroup']
export const DropdownMenuRadioItem: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuRadioItem']
export const DropdownMenuSeparator: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuSeparator']
export const DropdownMenuShortcut: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuShortcut']
export const DropdownMenuSub: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuSub']
export const DropdownMenuSubContent: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuSubContent']
export const DropdownMenuSubTrigger: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuSubTrigger']
export const DropdownMenuTrigger: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuTrigger']
export const DropdownMenuPortal: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuPortal']
export const Drawer: typeof import("../app/components/ui/drawer/index")['Drawer']
export const DrawerClose: typeof import("../app/components/ui/drawer/index")['DrawerClose']
export const DrawerContent: typeof import("../app/components/ui/drawer/index")['DrawerContent']
export const DrawerDescription: typeof import("../app/components/ui/drawer/index")['DrawerDescription']
export const DrawerFooter: typeof import("../app/components/ui/drawer/index")['DrawerFooter']
export const DrawerHeader: typeof import("../app/components/ui/drawer/index")['DrawerHeader']
export const DrawerOverlay: typeof import("../app/components/ui/drawer/index")['DrawerOverlay']
export const DrawerTitle: typeof import("../app/components/ui/drawer/index")['DrawerTitle']
export const DrawerTrigger: typeof import("../app/components/ui/drawer/index")['DrawerTrigger']
export const Field: typeof import("../app/components/ui/field/index")['Field']
export const FieldContent: typeof import("../app/components/ui/field/index")['FieldContent']
export const FieldDescription: typeof import("../app/components/ui/field/index")['FieldDescription']
export const FieldError: typeof import("../app/components/ui/field/index")['FieldError']
export const FieldGroup: typeof import("../app/components/ui/field/index")['FieldGroup']
export const FieldLabel: typeof import("../app/components/ui/field/index")['FieldLabel']
export const FieldLegend: typeof import("../app/components/ui/field/index")['FieldLegend']
export const FieldSeparator: typeof import("../app/components/ui/field/index")['FieldSeparator']
export const FieldSet: typeof import("../app/components/ui/field/index")['FieldSet']
export const FieldTitle: typeof import("../app/components/ui/field/index")['FieldTitle']
export const FormControl: typeof import("../app/components/ui/form/index")['FormControl']
export const FormDescription: typeof import("../app/components/ui/form/index")['FormDescription']
export const FormItem: typeof import("../app/components/ui/form/index")['FormItem']
export const FormLabel: typeof import("../app/components/ui/form/index")['FormLabel']
export const FormMessage: typeof import("../app/components/ui/form/index")['FormMessage']
export const FORMITEMINJECTIONKEY: typeof import("../app/components/ui/form/index")['FORM_ITEM_INJECTION_KEY']
export const Form: typeof import("../app/components/ui/form/index")['Form']
export const FormField: typeof import("../app/components/ui/form/index")['FormField']
export const FormFieldArray: typeof import("../app/components/ui/form/index")['FormFieldArray']
export const Input: typeof import("../app/components/ui/input/index")['Input']
export const HoverCard: typeof import("../app/components/ui/hover-card/index")['HoverCard']
export const HoverCardContent: typeof import("../app/components/ui/hover-card/index")['HoverCardContent']
export const HoverCardTrigger: typeof import("../app/components/ui/hover-card/index")['HoverCardTrigger']
export const Empty: typeof import("../app/components/ui/empty/index")['Empty']
export const EmptyContent: typeof import("../app/components/ui/empty/index")['EmptyContent']
export const EmptyDescription: typeof import("../app/components/ui/empty/index")['EmptyDescription']
export const EmptyHeader: typeof import("../app/components/ui/empty/index")['EmptyHeader']
export const EmptyMedia: typeof import("../app/components/ui/empty/index")['EmptyMedia']
export const EmptyTitle: typeof import("../app/components/ui/empty/index")['EmptyTitle']
export const InputGroup: typeof import("../app/components/ui/input-group/index")['InputGroup']
export const InputGroupAddon: typeof import("../app/components/ui/input-group/index")['InputGroupAddon']
export const InputGroupButton: typeof import("../app/components/ui/input-group/index")['InputGroupButton']
export const InputGroupInput: typeof import("../app/components/ui/input-group/index")['InputGroupInput']
export const InputGroupText: typeof import("../app/components/ui/input-group/index")['InputGroupText']
export const InputGroupTextarea: typeof import("../app/components/ui/input-group/index")['InputGroupTextarea']
export const InputOTP: typeof import("../app/components/ui/input-otp/index")['InputOTP']
export const InputOTPGroup: typeof import("../app/components/ui/input-otp/index")['InputOTPGroup']
export const InputOTPSeparator: typeof import("../app/components/ui/input-otp/index")['InputOTPSeparator']
export const InputOTPSlot: typeof import("../app/components/ui/input-otp/index")['InputOTPSlot']
export const Item: typeof import("../app/components/ui/item/index")['Item']
export const ItemActions: typeof import("../app/components/ui/item/index")['ItemActions']
export const ItemContent: typeof import("../app/components/ui/item/index")['ItemContent']
export const ItemDescription: typeof import("../app/components/ui/item/index")['ItemDescription']
export const ItemFooter: typeof import("../app/components/ui/item/index")['ItemFooter']
export const ItemGroup: typeof import("../app/components/ui/item/index")['ItemGroup']
export const ItemHeader: typeof import("../app/components/ui/item/index")['ItemHeader']
export const ItemMedia: typeof import("../app/components/ui/item/index")['ItemMedia']
export const ItemSeparator: typeof import("../app/components/ui/item/index")['ItemSeparator']
export const ItemTitle: typeof import("../app/components/ui/item/index")['ItemTitle']
export const Kbd: typeof import("../app/components/ui/kbd/index")['Kbd']
export const KbdGroup: typeof import("../app/components/ui/kbd/index")['KbdGroup']
export const Menubar: typeof import("../app/components/ui/menubar/index")['Menubar']
export const MenubarCheckboxItem: typeof import("../app/components/ui/menubar/index")['MenubarCheckboxItem']
export const MenubarContent: typeof import("../app/components/ui/menubar/index")['MenubarContent']
export const MenubarGroup: typeof import("../app/components/ui/menubar/index")['MenubarGroup']
export const MenubarItem: typeof import("../app/components/ui/menubar/index")['MenubarItem']
export const MenubarLabel: typeof import("../app/components/ui/menubar/index")['MenubarLabel']
export const MenubarMenu: typeof import("../app/components/ui/menubar/index")['MenubarMenu']
export const MenubarRadioGroup: typeof import("../app/components/ui/menubar/index")['MenubarRadioGroup']
export const MenubarRadioItem: typeof import("../app/components/ui/menubar/index")['MenubarRadioItem']
export const MenubarSeparator: typeof import("../app/components/ui/menubar/index")['MenubarSeparator']
export const MenubarShortcut: typeof import("../app/components/ui/menubar/index")['MenubarShortcut']
export const MenubarSub: typeof import("../app/components/ui/menubar/index")['MenubarSub']
export const MenubarSubContent: typeof import("../app/components/ui/menubar/index")['MenubarSubContent']
export const MenubarSubTrigger: typeof import("../app/components/ui/menubar/index")['MenubarSubTrigger']
export const MenubarTrigger: typeof import("../app/components/ui/menubar/index")['MenubarTrigger']
export const NativeSelect: typeof import("../app/components/ui/native-select/index")['NativeSelect']
export const NativeSelectOptGroup: typeof import("../app/components/ui/native-select/index")['NativeSelectOptGroup']
export const NativeSelectOption: typeof import("../app/components/ui/native-select/index")['NativeSelectOption']
export const Pagination: typeof import("../app/components/ui/pagination/index")['Pagination']
export const PaginationContent: typeof import("../app/components/ui/pagination/index")['PaginationContent']
export const PaginationEllipsis: typeof import("../app/components/ui/pagination/index")['PaginationEllipsis']
export const PaginationFirst: typeof import("../app/components/ui/pagination/index")['PaginationFirst']
export const PaginationItem: typeof import("../app/components/ui/pagination/index")['PaginationItem']
export const PaginationLast: typeof import("../app/components/ui/pagination/index")['PaginationLast']
export const PaginationNext: typeof import("../app/components/ui/pagination/index")['PaginationNext']
export const PaginationPrevious: typeof import("../app/components/ui/pagination/index")['PaginationPrevious']
export const NumberField: typeof import("../app/components/ui/number-field/index")['NumberField']
export const NumberFieldContent: typeof import("../app/components/ui/number-field/index")['NumberFieldContent']
export const NumberFieldDecrement: typeof import("../app/components/ui/number-field/index")['NumberFieldDecrement']
export const NumberFieldIncrement: typeof import("../app/components/ui/number-field/index")['NumberFieldIncrement']
export const NumberFieldInput: typeof import("../app/components/ui/number-field/index")['NumberFieldInput']
export const PinInput: typeof import("../app/components/ui/pin-input/index")['PinInput']
export const PinInputGroup: typeof import("../app/components/ui/pin-input/index")['PinInputGroup']
export const PinInputSeparator: typeof import("../app/components/ui/pin-input/index")['PinInputSeparator']
export const PinInputSlot: typeof import("../app/components/ui/pin-input/index")['PinInputSlot']
export const Popover: typeof import("../app/components/ui/popover/index")['Popover']
export const PopoverAnchor: typeof import("../app/components/ui/popover/index")['PopoverAnchor']
export const PopoverContent: typeof import("../app/components/ui/popover/index")['PopoverContent']
export const PopoverTrigger: typeof import("../app/components/ui/popover/index")['PopoverTrigger']
export const Label: typeof import("../app/components/ui/label/index")['Label']
export const NavigationMenu: typeof import("../app/components/ui/navigation-menu/index")['NavigationMenu']
export const NavigationMenuContent: typeof import("../app/components/ui/navigation-menu/index")['NavigationMenuContent']
export const NavigationMenuIndicator: typeof import("../app/components/ui/navigation-menu/index")['NavigationMenuIndicator']
export const NavigationMenuItem: typeof import("../app/components/ui/navigation-menu/index")['NavigationMenuItem']
export const NavigationMenuLink: typeof import("../app/components/ui/navigation-menu/index")['NavigationMenuLink']
export const NavigationMenuList: typeof import("../app/components/ui/navigation-menu/index")['NavigationMenuList']
export const NavigationMenuTrigger: typeof import("../app/components/ui/navigation-menu/index")['NavigationMenuTrigger']
export const NavigationMenuViewport: typeof import("../app/components/ui/navigation-menu/index")['NavigationMenuViewport']
export const RadioGroup: typeof import("../app/components/ui/radio-group/index")['RadioGroup']
export const RadioGroupItem: typeof import("../app/components/ui/radio-group/index")['RadioGroupItem']
export const ResizableHandle: typeof import("../app/components/ui/resizable/index")['ResizableHandle']
export const ResizablePanel: typeof import("../app/components/ui/resizable/index")['ResizablePanel']
export const ResizablePanelGroup: typeof import("../app/components/ui/resizable/index")['ResizablePanelGroup']
export const Select: typeof import("../app/components/ui/select/index")['Select']
export const SelectContent: typeof import("../app/components/ui/select/index")['SelectContent']
export const SelectGroup: typeof import("../app/components/ui/select/index")['SelectGroup']
export const SelectItem: typeof import("../app/components/ui/select/index")['SelectItem']
export const SelectItemText: typeof import("../app/components/ui/select/index")['SelectItemText']
export const SelectLabel: typeof import("../app/components/ui/select/index")['SelectLabel']
export const SelectScrollDownButton: typeof import("../app/components/ui/select/index")['SelectScrollDownButton']
export const SelectScrollUpButton: typeof import("../app/components/ui/select/index")['SelectScrollUpButton']
export const SelectSeparator: typeof import("../app/components/ui/select/index")['SelectSeparator']
export const SelectTrigger: typeof import("../app/components/ui/select/index")['SelectTrigger']
export const SelectValue: typeof import("../app/components/ui/select/index")['SelectValue']
export const ScrollArea: typeof import("../app/components/ui/scroll-area/index")['ScrollArea']
export const ScrollBar: typeof import("../app/components/ui/scroll-area/index")['ScrollBar']
export const Separator: typeof import("../app/components/ui/separator/index")['Separator']
export const Sidebar: typeof import("../app/components/ui/sidebar/index")['Sidebar']
export const SidebarContent: typeof import("../app/components/ui/sidebar/index")['SidebarContent']
export const SidebarFooter: typeof import("../app/components/ui/sidebar/index")['SidebarFooter']
export const SidebarGroup: typeof import("../app/components/ui/sidebar/index")['SidebarGroup']
export const SidebarGroupAction: typeof import("../app/components/ui/sidebar/index")['SidebarGroupAction']
export const SidebarGroupContent: typeof import("../app/components/ui/sidebar/index")['SidebarGroupContent']
export const SidebarGroupLabel: typeof import("../app/components/ui/sidebar/index")['SidebarGroupLabel']
export const SidebarHeader: typeof import("../app/components/ui/sidebar/index")['SidebarHeader']
export const SidebarInput: typeof import("../app/components/ui/sidebar/index")['SidebarInput']
export const SidebarInset: typeof import("../app/components/ui/sidebar/index")['SidebarInset']
export const SidebarMenu: typeof import("../app/components/ui/sidebar/index")['SidebarMenu']
export const SidebarMenuAction: typeof import("../app/components/ui/sidebar/index")['SidebarMenuAction']
export const SidebarMenuBadge: typeof import("../app/components/ui/sidebar/index")['SidebarMenuBadge']
export const SidebarMenuButton: typeof import("../app/components/ui/sidebar/index")['SidebarMenuButton']
export const SidebarMenuItem: typeof import("../app/components/ui/sidebar/index")['SidebarMenuItem']
export const SidebarMenuSkeleton: typeof import("../app/components/ui/sidebar/index")['SidebarMenuSkeleton']
export const SidebarMenuSub: typeof import("../app/components/ui/sidebar/index")['SidebarMenuSub']
export const SidebarMenuSubButton: typeof import("../app/components/ui/sidebar/index")['SidebarMenuSubButton']
export const SidebarMenuSubItem: typeof import("../app/components/ui/sidebar/index")['SidebarMenuSubItem']
export const SidebarProvider: typeof import("../app/components/ui/sidebar/index")['SidebarProvider']
export const SidebarRail: typeof import("../app/components/ui/sidebar/index")['SidebarRail']
export const SidebarSeparator: typeof import("../app/components/ui/sidebar/index")['SidebarSeparator']
export const SidebarTrigger: typeof import("../app/components/ui/sidebar/index")['SidebarTrigger']
export const Skeleton: typeof import("../app/components/ui/skeleton/index")['Skeleton']
export const Progress: typeof import("../app/components/ui/progress/index")['Progress']
export const Sheet: typeof import("../app/components/ui/sheet/index")['Sheet']
export const SheetClose: typeof import("../app/components/ui/sheet/index")['SheetClose']
export const SheetContent: typeof import("../app/components/ui/sheet/index")['SheetContent']
export const SheetDescription: typeof import("../app/components/ui/sheet/index")['SheetDescription']
export const SheetFooter: typeof import("../app/components/ui/sheet/index")['SheetFooter']
export const SheetHeader: typeof import("../app/components/ui/sheet/index")['SheetHeader']
export const SheetTitle: typeof import("../app/components/ui/sheet/index")['SheetTitle']
export const SheetTrigger: typeof import("../app/components/ui/sheet/index")['SheetTrigger']
export const Spinner: typeof import("../app/components/ui/spinner/index")['Spinner']
export const Toaster: typeof import("../app/components/ui/sonner/index")['Toaster']
export const RangeCalendar: typeof import("../app/components/ui/range-calendar/index")['RangeCalendar']
export const RangeCalendarCell: typeof import("../app/components/ui/range-calendar/index")['RangeCalendarCell']
export const RangeCalendarCellTrigger: typeof import("../app/components/ui/range-calendar/index")['RangeCalendarCellTrigger']
export const RangeCalendarGrid: typeof import("../app/components/ui/range-calendar/index")['RangeCalendarGrid']
export const RangeCalendarGridBody: typeof import("../app/components/ui/range-calendar/index")['RangeCalendarGridBody']
export const RangeCalendarGridHead: typeof import("../app/components/ui/range-calendar/index")['RangeCalendarGridHead']
export const RangeCalendarGridRow: typeof import("../app/components/ui/range-calendar/index")['RangeCalendarGridRow']
export const RangeCalendarHeadCell: typeof import("../app/components/ui/range-calendar/index")['RangeCalendarHeadCell']
export const RangeCalendarHeader: typeof import("../app/components/ui/range-calendar/index")['RangeCalendarHeader']
export const RangeCalendarHeading: typeof import("../app/components/ui/range-calendar/index")['RangeCalendarHeading']
export const RangeCalendarNextButton: typeof import("../app/components/ui/range-calendar/index")['RangeCalendarNextButton']
export const RangeCalendarPrevButton: typeof import("../app/components/ui/range-calendar/index")['RangeCalendarPrevButton']
export const Slider: typeof import("../app/components/ui/slider/index")['Slider']
export const Stepper: typeof import("../app/components/ui/stepper/index")['Stepper']
export const StepperDescription: typeof import("../app/components/ui/stepper/index")['StepperDescription']
export const StepperIndicator: typeof import("../app/components/ui/stepper/index")['StepperIndicator']
export const StepperItem: typeof import("../app/components/ui/stepper/index")['StepperItem']
export const StepperSeparator: typeof import("../app/components/ui/stepper/index")['StepperSeparator']
export const StepperTitle: typeof import("../app/components/ui/stepper/index")['StepperTitle']
export const StepperTrigger: typeof import("../app/components/ui/stepper/index")['StepperTrigger']
export const Table: typeof import("../app/components/ui/table/index")['Table']
export const TableBody: typeof import("../app/components/ui/table/index")['TableBody']
export const TableCaption: typeof import("../app/components/ui/table/index")['TableCaption']
export const TableCell: typeof import("../app/components/ui/table/index")['TableCell']
export const TableEmpty: typeof import("../app/components/ui/table/index")['TableEmpty']
export const TableFooter: typeof import("../app/components/ui/table/index")['TableFooter']
export const TableHead: typeof import("../app/components/ui/table/index")['TableHead']
export const TableHeader: typeof import("../app/components/ui/table/index")['TableHeader']
export const TableRow: typeof import("../app/components/ui/table/index")['TableRow']
export const Switch: typeof import("../app/components/ui/switch/index")['Switch']
export const Textarea: typeof import("../app/components/ui/textarea/index")['Textarea']
export const Tabs: typeof import("../app/components/ui/tabs/index")['Tabs']
export const TabsContent: typeof import("../app/components/ui/tabs/index")['TabsContent']
export const TabsList: typeof import("../app/components/ui/tabs/index")['TabsList']
export const TabsTrigger: typeof import("../app/components/ui/tabs/index")['TabsTrigger']
export const Toggle: typeof import("../app/components/ui/toggle/index")['Toggle']
export const TagsInput: typeof import("../app/components/ui/tags-input/index")['TagsInput']
export const TagsInputInput: typeof import("../app/components/ui/tags-input/index")['TagsInputInput']
export const TagsInputItem: typeof import("../app/components/ui/tags-input/index")['TagsInputItem']
export const TagsInputItemDelete: typeof import("../app/components/ui/tags-input/index")['TagsInputItemDelete']
export const TagsInputItemText: typeof import("../app/components/ui/tags-input/index")['TagsInputItemText']
export const Tooltip: typeof import("../app/components/ui/tooltip/index")['Tooltip']
export const TooltipContent: typeof import("../app/components/ui/tooltip/index")['TooltipContent']
export const TooltipProvider: typeof import("../app/components/ui/tooltip/index")['TooltipProvider']
export const TooltipTrigger: typeof import("../app/components/ui/tooltip/index")['TooltipTrigger']
export const ToggleGroup: typeof import("../app/components/ui/toggle-group/index")['ToggleGroup']
export const ToggleGroupItem: typeof import("../app/components/ui/toggle-group/index")['ToggleGroupItem']
export const Icon: typeof import("../node_modules/@nuxt/icon/dist/runtime/components/index")['default']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyEditorMonacoEditor: LazyComponent<typeof import("../app/components/editor/MonacoEditor.vue")['default']>
export const LazyEditorPreviewCanvas: LazyComponent<typeof import("../app/components/editor/PreviewCanvas.vue")['default']>
export const LazyEditorTimeline: LazyComponent<typeof import("../app/components/editor/Timeline.vue")['default']>
export const LazyNuxtWelcome: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']>
export const LazyNuxtLayout: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
export const LazyNuxtErrorBoundary: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
export const LazyClientOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']>
export const LazyDevOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']>
export const LazyServerPlaceholder: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyNuxtLink: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']>
export const LazyNuxtLoadingIndicator: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
export const LazyNuxtTime: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
export const LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
export const LazyNuxtAnnouncer: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-announcer")['default']>
export const LazyNuxtImg: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']>
export const LazyNuxtPicture: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']>
export const LazyAccordion: LazyComponent<typeof import("../app/components/ui/accordion/index")['Accordion']>
export const LazyAccordionContent: LazyComponent<typeof import("../app/components/ui/accordion/index")['AccordionContent']>
export const LazyAccordionItem: LazyComponent<typeof import("../app/components/ui/accordion/index")['AccordionItem']>
export const LazyAccordionTrigger: LazyComponent<typeof import("../app/components/ui/accordion/index")['AccordionTrigger']>
export const LazyAlert: LazyComponent<typeof import("../app/components/ui/alert/index")['Alert']>
export const LazyAlertDescription: LazyComponent<typeof import("../app/components/ui/alert/index")['AlertDescription']>
export const LazyAlertTitle: LazyComponent<typeof import("../app/components/ui/alert/index")['AlertTitle']>
export const LazyAlertDialog: LazyComponent<typeof import("../app/components/ui/alert-dialog/index")['AlertDialog']>
export const LazyAlertDialogAction: LazyComponent<typeof import("../app/components/ui/alert-dialog/index")['AlertDialogAction']>
export const LazyAlertDialogCancel: LazyComponent<typeof import("../app/components/ui/alert-dialog/index")['AlertDialogCancel']>
export const LazyAlertDialogContent: LazyComponent<typeof import("../app/components/ui/alert-dialog/index")['AlertDialogContent']>
export const LazyAlertDialogDescription: LazyComponent<typeof import("../app/components/ui/alert-dialog/index")['AlertDialogDescription']>
export const LazyAlertDialogFooter: LazyComponent<typeof import("../app/components/ui/alert-dialog/index")['AlertDialogFooter']>
export const LazyAlertDialogHeader: LazyComponent<typeof import("../app/components/ui/alert-dialog/index")['AlertDialogHeader']>
export const LazyAlertDialogTitle: LazyComponent<typeof import("../app/components/ui/alert-dialog/index")['AlertDialogTitle']>
export const LazyAlertDialogTrigger: LazyComponent<typeof import("../app/components/ui/alert-dialog/index")['AlertDialogTrigger']>
export const LazyAvatar: LazyComponent<typeof import("../app/components/ui/avatar/index")['Avatar']>
export const LazyAvatarFallback: LazyComponent<typeof import("../app/components/ui/avatar/index")['AvatarFallback']>
export const LazyAvatarImage: LazyComponent<typeof import("../app/components/ui/avatar/index")['AvatarImage']>
export const LazyBadge: LazyComponent<typeof import("../app/components/ui/badge/index")['Badge']>
export const LazyBreadcrumb: LazyComponent<typeof import("../app/components/ui/breadcrumb/index")['Breadcrumb']>
export const LazyBreadcrumbEllipsis: LazyComponent<typeof import("../app/components/ui/breadcrumb/index")['BreadcrumbEllipsis']>
export const LazyBreadcrumbItem: LazyComponent<typeof import("../app/components/ui/breadcrumb/index")['BreadcrumbItem']>
export const LazyBreadcrumbLink: LazyComponent<typeof import("../app/components/ui/breadcrumb/index")['BreadcrumbLink']>
export const LazyBreadcrumbList: LazyComponent<typeof import("../app/components/ui/breadcrumb/index")['BreadcrumbList']>
export const LazyBreadcrumbPage: LazyComponent<typeof import("../app/components/ui/breadcrumb/index")['BreadcrumbPage']>
export const LazyBreadcrumbSeparator: LazyComponent<typeof import("../app/components/ui/breadcrumb/index")['BreadcrumbSeparator']>
export const LazyButton: LazyComponent<typeof import("../app/components/ui/button/index")['Button']>
export const LazyCalendar: LazyComponent<typeof import("../app/components/ui/calendar/index")['Calendar']>
export const LazyCalendarCell: LazyComponent<typeof import("../app/components/ui/calendar/index")['CalendarCell']>
export const LazyCalendarCellTrigger: LazyComponent<typeof import("../app/components/ui/calendar/index")['CalendarCellTrigger']>
export const LazyCalendarGrid: LazyComponent<typeof import("../app/components/ui/calendar/index")['CalendarGrid']>
export const LazyCalendarGridBody: LazyComponent<typeof import("../app/components/ui/calendar/index")['CalendarGridBody']>
export const LazyCalendarGridHead: LazyComponent<typeof import("../app/components/ui/calendar/index")['CalendarGridHead']>
export const LazyCalendarGridRow: LazyComponent<typeof import("../app/components/ui/calendar/index")['CalendarGridRow']>
export const LazyCalendarHeadCell: LazyComponent<typeof import("../app/components/ui/calendar/index")['CalendarHeadCell']>
export const LazyCalendarHeader: LazyComponent<typeof import("../app/components/ui/calendar/index")['CalendarHeader']>
export const LazyCalendarHeading: LazyComponent<typeof import("../app/components/ui/calendar/index")['CalendarHeading']>
export const LazyCalendarNextButton: LazyComponent<typeof import("../app/components/ui/calendar/index")['CalendarNextButton']>
export const LazyCalendarPrevButton: LazyComponent<typeof import("../app/components/ui/calendar/index")['CalendarPrevButton']>
export const LazyButtonGroup: LazyComponent<typeof import("../app/components/ui/button-group/index")['ButtonGroup']>
export const LazyButtonGroupSeparator: LazyComponent<typeof import("../app/components/ui/button-group/index")['ButtonGroupSeparator']>
export const LazyButtonGroupText: LazyComponent<typeof import("../app/components/ui/button-group/index")['ButtonGroupText']>
export const LazyChartContainer: LazyComponent<typeof import("../app/components/ui/chart/index")['ChartContainer']>
export const LazyChartLegendContent: LazyComponent<typeof import("../app/components/ui/chart/index")['ChartLegendContent']>
export const LazyChartTooltipContent: LazyComponent<typeof import("../app/components/ui/chart/index")['ChartTooltipContent']>
export const LazyChartCrosshair: LazyComponent<typeof import("../app/components/ui/chart/index")['ChartCrosshair']>
export const LazyChartTooltip: LazyComponent<typeof import("../app/components/ui/chart/index")['ChartTooltip']>
export const LazyCarousel: LazyComponent<typeof import("../app/components/ui/carousel/index")['Carousel']>
export const LazyCarouselContent: LazyComponent<typeof import("../app/components/ui/carousel/index")['CarouselContent']>
export const LazyCarouselItem: LazyComponent<typeof import("../app/components/ui/carousel/index")['CarouselItem']>
export const LazyCarouselNext: LazyComponent<typeof import("../app/components/ui/carousel/index")['CarouselNext']>
export const LazyCarouselPrevious: LazyComponent<typeof import("../app/components/ui/carousel/index")['CarouselPrevious']>
export const LazyCarouselApi: LazyComponent<typeof import("../app/components/ui/carousel/index")['CarouselApi']>
export const LazyAspectRatio: LazyComponent<typeof import("../app/components/ui/aspect-ratio/index")['AspectRatio']>
export const LazyCard: LazyComponent<typeof import("../app/components/ui/card/index")['Card']>
export const LazyCardAction: LazyComponent<typeof import("../app/components/ui/card/index")['CardAction']>
export const LazyCardContent: LazyComponent<typeof import("../app/components/ui/card/index")['CardContent']>
export const LazyCardDescription: LazyComponent<typeof import("../app/components/ui/card/index")['CardDescription']>
export const LazyCardFooter: LazyComponent<typeof import("../app/components/ui/card/index")['CardFooter']>
export const LazyCardHeader: LazyComponent<typeof import("../app/components/ui/card/index")['CardHeader']>
export const LazyCardTitle: LazyComponent<typeof import("../app/components/ui/card/index")['CardTitle']>
export const LazyCollapsible: LazyComponent<typeof import("../app/components/ui/collapsible/index")['Collapsible']>
export const LazyCollapsibleContent: LazyComponent<typeof import("../app/components/ui/collapsible/index")['CollapsibleContent']>
export const LazyCollapsibleTrigger: LazyComponent<typeof import("../app/components/ui/collapsible/index")['CollapsibleTrigger']>
export const LazyCheckbox: LazyComponent<typeof import("../app/components/ui/checkbox/index")['Checkbox']>
export const LazyDialog: LazyComponent<typeof import("../app/components/ui/dialog/index")['Dialog']>
export const LazyDialogClose: LazyComponent<typeof import("../app/components/ui/dialog/index")['DialogClose']>
export const LazyDialogContent: LazyComponent<typeof import("../app/components/ui/dialog/index")['DialogContent']>
export const LazyDialogDescription: LazyComponent<typeof import("../app/components/ui/dialog/index")['DialogDescription']>
export const LazyDialogFooter: LazyComponent<typeof import("../app/components/ui/dialog/index")['DialogFooter']>
export const LazyDialogHeader: LazyComponent<typeof import("../app/components/ui/dialog/index")['DialogHeader']>
export const LazyDialogOverlay: LazyComponent<typeof import("../app/components/ui/dialog/index")['DialogOverlay']>
export const LazyDialogScrollContent: LazyComponent<typeof import("../app/components/ui/dialog/index")['DialogScrollContent']>
export const LazyDialogTitle: LazyComponent<typeof import("../app/components/ui/dialog/index")['DialogTitle']>
export const LazyDialogTrigger: LazyComponent<typeof import("../app/components/ui/dialog/index")['DialogTrigger']>
export const LazyContextMenu: LazyComponent<typeof import("../app/components/ui/context-menu/index")['ContextMenu']>
export const LazyContextMenuCheckboxItem: LazyComponent<typeof import("../app/components/ui/context-menu/index")['ContextMenuCheckboxItem']>
export const LazyContextMenuContent: LazyComponent<typeof import("../app/components/ui/context-menu/index")['ContextMenuContent']>
export const LazyContextMenuGroup: LazyComponent<typeof import("../app/components/ui/context-menu/index")['ContextMenuGroup']>
export const LazyContextMenuItem: LazyComponent<typeof import("../app/components/ui/context-menu/index")['ContextMenuItem']>
export const LazyContextMenuLabel: LazyComponent<typeof import("../app/components/ui/context-menu/index")['ContextMenuLabel']>
export const LazyContextMenuRadioGroup: LazyComponent<typeof import("../app/components/ui/context-menu/index")['ContextMenuRadioGroup']>
export const LazyContextMenuRadioItem: LazyComponent<typeof import("../app/components/ui/context-menu/index")['ContextMenuRadioItem']>
export const LazyContextMenuSeparator: LazyComponent<typeof import("../app/components/ui/context-menu/index")['ContextMenuSeparator']>
export const LazyContextMenuShortcut: LazyComponent<typeof import("../app/components/ui/context-menu/index")['ContextMenuShortcut']>
export const LazyContextMenuSub: LazyComponent<typeof import("../app/components/ui/context-menu/index")['ContextMenuSub']>
export const LazyContextMenuSubContent: LazyComponent<typeof import("../app/components/ui/context-menu/index")['ContextMenuSubContent']>
export const LazyContextMenuSubTrigger: LazyComponent<typeof import("../app/components/ui/context-menu/index")['ContextMenuSubTrigger']>
export const LazyContextMenuTrigger: LazyComponent<typeof import("../app/components/ui/context-menu/index")['ContextMenuTrigger']>
export const LazyCommand: LazyComponent<typeof import("../app/components/ui/command/index")['Command']>
export const LazyCommandDialog: LazyComponent<typeof import("../app/components/ui/command/index")['CommandDialog']>
export const LazyCommandEmpty: LazyComponent<typeof import("../app/components/ui/command/index")['CommandEmpty']>
export const LazyCommandGroup: LazyComponent<typeof import("../app/components/ui/command/index")['CommandGroup']>
export const LazyCommandInput: LazyComponent<typeof import("../app/components/ui/command/index")['CommandInput']>
export const LazyCommandItem: LazyComponent<typeof import("../app/components/ui/command/index")['CommandItem']>
export const LazyCommandList: LazyComponent<typeof import("../app/components/ui/command/index")['CommandList']>
export const LazyCommandSeparator: LazyComponent<typeof import("../app/components/ui/command/index")['CommandSeparator']>
export const LazyCommandShortcut: LazyComponent<typeof import("../app/components/ui/command/index")['CommandShortcut']>
export const LazyCombobox: LazyComponent<typeof import("../app/components/ui/combobox/index")['Combobox']>
export const LazyComboboxAnchor: LazyComponent<typeof import("../app/components/ui/combobox/index")['ComboboxAnchor']>
export const LazyComboboxEmpty: LazyComponent<typeof import("../app/components/ui/combobox/index")['ComboboxEmpty']>
export const LazyComboboxGroup: LazyComponent<typeof import("../app/components/ui/combobox/index")['ComboboxGroup']>
export const LazyComboboxInput: LazyComponent<typeof import("../app/components/ui/combobox/index")['ComboboxInput']>
export const LazyComboboxItem: LazyComponent<typeof import("../app/components/ui/combobox/index")['ComboboxItem']>
export const LazyComboboxItemIndicator: LazyComponent<typeof import("../app/components/ui/combobox/index")['ComboboxItemIndicator']>
export const LazyComboboxList: LazyComponent<typeof import("../app/components/ui/combobox/index")['ComboboxList']>
export const LazyComboboxSeparator: LazyComponent<typeof import("../app/components/ui/combobox/index")['ComboboxSeparator']>
export const LazyComboboxViewport: LazyComponent<typeof import("../app/components/ui/combobox/index")['ComboboxViewport']>
export const LazyComboboxCancel: LazyComponent<typeof import("../app/components/ui/combobox/index")['ComboboxCancel']>
export const LazyComboboxTrigger: LazyComponent<typeof import("../app/components/ui/combobox/index")['ComboboxTrigger']>
export const LazyDropdownMenu: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenu']>
export const LazyDropdownMenuCheckboxItem: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuCheckboxItem']>
export const LazyDropdownMenuContent: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuContent']>
export const LazyDropdownMenuGroup: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuGroup']>
export const LazyDropdownMenuItem: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuItem']>
export const LazyDropdownMenuLabel: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuLabel']>
export const LazyDropdownMenuRadioGroup: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuRadioGroup']>
export const LazyDropdownMenuRadioItem: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuRadioItem']>
export const LazyDropdownMenuSeparator: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuSeparator']>
export const LazyDropdownMenuShortcut: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuShortcut']>
export const LazyDropdownMenuSub: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuSub']>
export const LazyDropdownMenuSubContent: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuSubContent']>
export const LazyDropdownMenuSubTrigger: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuSubTrigger']>
export const LazyDropdownMenuTrigger: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuTrigger']>
export const LazyDropdownMenuPortal: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuPortal']>
export const LazyDrawer: LazyComponent<typeof import("../app/components/ui/drawer/index")['Drawer']>
export const LazyDrawerClose: LazyComponent<typeof import("../app/components/ui/drawer/index")['DrawerClose']>
export const LazyDrawerContent: LazyComponent<typeof import("../app/components/ui/drawer/index")['DrawerContent']>
export const LazyDrawerDescription: LazyComponent<typeof import("../app/components/ui/drawer/index")['DrawerDescription']>
export const LazyDrawerFooter: LazyComponent<typeof import("../app/components/ui/drawer/index")['DrawerFooter']>
export const LazyDrawerHeader: LazyComponent<typeof import("../app/components/ui/drawer/index")['DrawerHeader']>
export const LazyDrawerOverlay: LazyComponent<typeof import("../app/components/ui/drawer/index")['DrawerOverlay']>
export const LazyDrawerTitle: LazyComponent<typeof import("../app/components/ui/drawer/index")['DrawerTitle']>
export const LazyDrawerTrigger: LazyComponent<typeof import("../app/components/ui/drawer/index")['DrawerTrigger']>
export const LazyField: LazyComponent<typeof import("../app/components/ui/field/index")['Field']>
export const LazyFieldContent: LazyComponent<typeof import("../app/components/ui/field/index")['FieldContent']>
export const LazyFieldDescription: LazyComponent<typeof import("../app/components/ui/field/index")['FieldDescription']>
export const LazyFieldError: LazyComponent<typeof import("../app/components/ui/field/index")['FieldError']>
export const LazyFieldGroup: LazyComponent<typeof import("../app/components/ui/field/index")['FieldGroup']>
export const LazyFieldLabel: LazyComponent<typeof import("../app/components/ui/field/index")['FieldLabel']>
export const LazyFieldLegend: LazyComponent<typeof import("../app/components/ui/field/index")['FieldLegend']>
export const LazyFieldSeparator: LazyComponent<typeof import("../app/components/ui/field/index")['FieldSeparator']>
export const LazyFieldSet: LazyComponent<typeof import("../app/components/ui/field/index")['FieldSet']>
export const LazyFieldTitle: LazyComponent<typeof import("../app/components/ui/field/index")['FieldTitle']>
export const LazyFormControl: LazyComponent<typeof import("../app/components/ui/form/index")['FormControl']>
export const LazyFormDescription: LazyComponent<typeof import("../app/components/ui/form/index")['FormDescription']>
export const LazyFormItem: LazyComponent<typeof import("../app/components/ui/form/index")['FormItem']>
export const LazyFormLabel: LazyComponent<typeof import("../app/components/ui/form/index")['FormLabel']>
export const LazyFormMessage: LazyComponent<typeof import("../app/components/ui/form/index")['FormMessage']>
export const LazyFORMITEMINJECTIONKEY: LazyComponent<typeof import("../app/components/ui/form/index")['FORM_ITEM_INJECTION_KEY']>
export const LazyForm: LazyComponent<typeof import("../app/components/ui/form/index")['Form']>
export const LazyFormField: LazyComponent<typeof import("../app/components/ui/form/index")['FormField']>
export const LazyFormFieldArray: LazyComponent<typeof import("../app/components/ui/form/index")['FormFieldArray']>
export const LazyInput: LazyComponent<typeof import("../app/components/ui/input/index")['Input']>
export const LazyHoverCard: LazyComponent<typeof import("../app/components/ui/hover-card/index")['HoverCard']>
export const LazyHoverCardContent: LazyComponent<typeof import("../app/components/ui/hover-card/index")['HoverCardContent']>
export const LazyHoverCardTrigger: LazyComponent<typeof import("../app/components/ui/hover-card/index")['HoverCardTrigger']>
export const LazyEmpty: LazyComponent<typeof import("../app/components/ui/empty/index")['Empty']>
export const LazyEmptyContent: LazyComponent<typeof import("../app/components/ui/empty/index")['EmptyContent']>
export const LazyEmptyDescription: LazyComponent<typeof import("../app/components/ui/empty/index")['EmptyDescription']>
export const LazyEmptyHeader: LazyComponent<typeof import("../app/components/ui/empty/index")['EmptyHeader']>
export const LazyEmptyMedia: LazyComponent<typeof import("../app/components/ui/empty/index")['EmptyMedia']>
export const LazyEmptyTitle: LazyComponent<typeof import("../app/components/ui/empty/index")['EmptyTitle']>
export const LazyInputGroup: LazyComponent<typeof import("../app/components/ui/input-group/index")['InputGroup']>
export const LazyInputGroupAddon: LazyComponent<typeof import("../app/components/ui/input-group/index")['InputGroupAddon']>
export const LazyInputGroupButton: LazyComponent<typeof import("../app/components/ui/input-group/index")['InputGroupButton']>
export const LazyInputGroupInput: LazyComponent<typeof import("../app/components/ui/input-group/index")['InputGroupInput']>
export const LazyInputGroupText: LazyComponent<typeof import("../app/components/ui/input-group/index")['InputGroupText']>
export const LazyInputGroupTextarea: LazyComponent<typeof import("../app/components/ui/input-group/index")['InputGroupTextarea']>
export const LazyInputOTP: LazyComponent<typeof import("../app/components/ui/input-otp/index")['InputOTP']>
export const LazyInputOTPGroup: LazyComponent<typeof import("../app/components/ui/input-otp/index")['InputOTPGroup']>
export const LazyInputOTPSeparator: LazyComponent<typeof import("../app/components/ui/input-otp/index")['InputOTPSeparator']>
export const LazyInputOTPSlot: LazyComponent<typeof import("../app/components/ui/input-otp/index")['InputOTPSlot']>
export const LazyItem: LazyComponent<typeof import("../app/components/ui/item/index")['Item']>
export const LazyItemActions: LazyComponent<typeof import("../app/components/ui/item/index")['ItemActions']>
export const LazyItemContent: LazyComponent<typeof import("../app/components/ui/item/index")['ItemContent']>
export const LazyItemDescription: LazyComponent<typeof import("../app/components/ui/item/index")['ItemDescription']>
export const LazyItemFooter: LazyComponent<typeof import("../app/components/ui/item/index")['ItemFooter']>
export const LazyItemGroup: LazyComponent<typeof import("../app/components/ui/item/index")['ItemGroup']>
export const LazyItemHeader: LazyComponent<typeof import("../app/components/ui/item/index")['ItemHeader']>
export const LazyItemMedia: LazyComponent<typeof import("../app/components/ui/item/index")['ItemMedia']>
export const LazyItemSeparator: LazyComponent<typeof import("../app/components/ui/item/index")['ItemSeparator']>
export const LazyItemTitle: LazyComponent<typeof import("../app/components/ui/item/index")['ItemTitle']>
export const LazyKbd: LazyComponent<typeof import("../app/components/ui/kbd/index")['Kbd']>
export const LazyKbdGroup: LazyComponent<typeof import("../app/components/ui/kbd/index")['KbdGroup']>
export const LazyMenubar: LazyComponent<typeof import("../app/components/ui/menubar/index")['Menubar']>
export const LazyMenubarCheckboxItem: LazyComponent<typeof import("../app/components/ui/menubar/index")['MenubarCheckboxItem']>
export const LazyMenubarContent: LazyComponent<typeof import("../app/components/ui/menubar/index")['MenubarContent']>
export const LazyMenubarGroup: LazyComponent<typeof import("../app/components/ui/menubar/index")['MenubarGroup']>
export const LazyMenubarItem: LazyComponent<typeof import("../app/components/ui/menubar/index")['MenubarItem']>
export const LazyMenubarLabel: LazyComponent<typeof import("../app/components/ui/menubar/index")['MenubarLabel']>
export const LazyMenubarMenu: LazyComponent<typeof import("../app/components/ui/menubar/index")['MenubarMenu']>
export const LazyMenubarRadioGroup: LazyComponent<typeof import("../app/components/ui/menubar/index")['MenubarRadioGroup']>
export const LazyMenubarRadioItem: LazyComponent<typeof import("../app/components/ui/menubar/index")['MenubarRadioItem']>
export const LazyMenubarSeparator: LazyComponent<typeof import("../app/components/ui/menubar/index")['MenubarSeparator']>
export const LazyMenubarShortcut: LazyComponent<typeof import("../app/components/ui/menubar/index")['MenubarShortcut']>
export const LazyMenubarSub: LazyComponent<typeof import("../app/components/ui/menubar/index")['MenubarSub']>
export const LazyMenubarSubContent: LazyComponent<typeof import("../app/components/ui/menubar/index")['MenubarSubContent']>
export const LazyMenubarSubTrigger: LazyComponent<typeof import("../app/components/ui/menubar/index")['MenubarSubTrigger']>
export const LazyMenubarTrigger: LazyComponent<typeof import("../app/components/ui/menubar/index")['MenubarTrigger']>
export const LazyNativeSelect: LazyComponent<typeof import("../app/components/ui/native-select/index")['NativeSelect']>
export const LazyNativeSelectOptGroup: LazyComponent<typeof import("../app/components/ui/native-select/index")['NativeSelectOptGroup']>
export const LazyNativeSelectOption: LazyComponent<typeof import("../app/components/ui/native-select/index")['NativeSelectOption']>
export const LazyPagination: LazyComponent<typeof import("../app/components/ui/pagination/index")['Pagination']>
export const LazyPaginationContent: LazyComponent<typeof import("../app/components/ui/pagination/index")['PaginationContent']>
export const LazyPaginationEllipsis: LazyComponent<typeof import("../app/components/ui/pagination/index")['PaginationEllipsis']>
export const LazyPaginationFirst: LazyComponent<typeof import("../app/components/ui/pagination/index")['PaginationFirst']>
export const LazyPaginationItem: LazyComponent<typeof import("../app/components/ui/pagination/index")['PaginationItem']>
export const LazyPaginationLast: LazyComponent<typeof import("../app/components/ui/pagination/index")['PaginationLast']>
export const LazyPaginationNext: LazyComponent<typeof import("../app/components/ui/pagination/index")['PaginationNext']>
export const LazyPaginationPrevious: LazyComponent<typeof import("../app/components/ui/pagination/index")['PaginationPrevious']>
export const LazyNumberField: LazyComponent<typeof import("../app/components/ui/number-field/index")['NumberField']>
export const LazyNumberFieldContent: LazyComponent<typeof import("../app/components/ui/number-field/index")['NumberFieldContent']>
export const LazyNumberFieldDecrement: LazyComponent<typeof import("../app/components/ui/number-field/index")['NumberFieldDecrement']>
export const LazyNumberFieldIncrement: LazyComponent<typeof import("../app/components/ui/number-field/index")['NumberFieldIncrement']>
export const LazyNumberFieldInput: LazyComponent<typeof import("../app/components/ui/number-field/index")['NumberFieldInput']>
export const LazyPinInput: LazyComponent<typeof import("../app/components/ui/pin-input/index")['PinInput']>
export const LazyPinInputGroup: LazyComponent<typeof import("../app/components/ui/pin-input/index")['PinInputGroup']>
export const LazyPinInputSeparator: LazyComponent<typeof import("../app/components/ui/pin-input/index")['PinInputSeparator']>
export const LazyPinInputSlot: LazyComponent<typeof import("../app/components/ui/pin-input/index")['PinInputSlot']>
export const LazyPopover: LazyComponent<typeof import("../app/components/ui/popover/index")['Popover']>
export const LazyPopoverAnchor: LazyComponent<typeof import("../app/components/ui/popover/index")['PopoverAnchor']>
export const LazyPopoverContent: LazyComponent<typeof import("../app/components/ui/popover/index")['PopoverContent']>
export const LazyPopoverTrigger: LazyComponent<typeof import("../app/components/ui/popover/index")['PopoverTrigger']>
export const LazyLabel: LazyComponent<typeof import("../app/components/ui/label/index")['Label']>
export const LazyNavigationMenu: LazyComponent<typeof import("../app/components/ui/navigation-menu/index")['NavigationMenu']>
export const LazyNavigationMenuContent: LazyComponent<typeof import("../app/components/ui/navigation-menu/index")['NavigationMenuContent']>
export const LazyNavigationMenuIndicator: LazyComponent<typeof import("../app/components/ui/navigation-menu/index")['NavigationMenuIndicator']>
export const LazyNavigationMenuItem: LazyComponent<typeof import("../app/components/ui/navigation-menu/index")['NavigationMenuItem']>
export const LazyNavigationMenuLink: LazyComponent<typeof import("../app/components/ui/navigation-menu/index")['NavigationMenuLink']>
export const LazyNavigationMenuList: LazyComponent<typeof import("../app/components/ui/navigation-menu/index")['NavigationMenuList']>
export const LazyNavigationMenuTrigger: LazyComponent<typeof import("../app/components/ui/navigation-menu/index")['NavigationMenuTrigger']>
export const LazyNavigationMenuViewport: LazyComponent<typeof import("../app/components/ui/navigation-menu/index")['NavigationMenuViewport']>
export const LazyRadioGroup: LazyComponent<typeof import("../app/components/ui/radio-group/index")['RadioGroup']>
export const LazyRadioGroupItem: LazyComponent<typeof import("../app/components/ui/radio-group/index")['RadioGroupItem']>
export const LazyResizableHandle: LazyComponent<typeof import("../app/components/ui/resizable/index")['ResizableHandle']>
export const LazyResizablePanel: LazyComponent<typeof import("../app/components/ui/resizable/index")['ResizablePanel']>
export const LazyResizablePanelGroup: LazyComponent<typeof import("../app/components/ui/resizable/index")['ResizablePanelGroup']>
export const LazySelect: LazyComponent<typeof import("../app/components/ui/select/index")['Select']>
export const LazySelectContent: LazyComponent<typeof import("../app/components/ui/select/index")['SelectContent']>
export const LazySelectGroup: LazyComponent<typeof import("../app/components/ui/select/index")['SelectGroup']>
export const LazySelectItem: LazyComponent<typeof import("../app/components/ui/select/index")['SelectItem']>
export const LazySelectItemText: LazyComponent<typeof import("../app/components/ui/select/index")['SelectItemText']>
export const LazySelectLabel: LazyComponent<typeof import("../app/components/ui/select/index")['SelectLabel']>
export const LazySelectScrollDownButton: LazyComponent<typeof import("../app/components/ui/select/index")['SelectScrollDownButton']>
export const LazySelectScrollUpButton: LazyComponent<typeof import("../app/components/ui/select/index")['SelectScrollUpButton']>
export const LazySelectSeparator: LazyComponent<typeof import("../app/components/ui/select/index")['SelectSeparator']>
export const LazySelectTrigger: LazyComponent<typeof import("../app/components/ui/select/index")['SelectTrigger']>
export const LazySelectValue: LazyComponent<typeof import("../app/components/ui/select/index")['SelectValue']>
export const LazyScrollArea: LazyComponent<typeof import("../app/components/ui/scroll-area/index")['ScrollArea']>
export const LazyScrollBar: LazyComponent<typeof import("../app/components/ui/scroll-area/index")['ScrollBar']>
export const LazySeparator: LazyComponent<typeof import("../app/components/ui/separator/index")['Separator']>
export const LazySidebar: LazyComponent<typeof import("../app/components/ui/sidebar/index")['Sidebar']>
export const LazySidebarContent: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarContent']>
export const LazySidebarFooter: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarFooter']>
export const LazySidebarGroup: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarGroup']>
export const LazySidebarGroupAction: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarGroupAction']>
export const LazySidebarGroupContent: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarGroupContent']>
export const LazySidebarGroupLabel: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarGroupLabel']>
export const LazySidebarHeader: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarHeader']>
export const LazySidebarInput: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarInput']>
export const LazySidebarInset: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarInset']>
export const LazySidebarMenu: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarMenu']>
export const LazySidebarMenuAction: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarMenuAction']>
export const LazySidebarMenuBadge: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarMenuBadge']>
export const LazySidebarMenuButton: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarMenuButton']>
export const LazySidebarMenuItem: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarMenuItem']>
export const LazySidebarMenuSkeleton: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarMenuSkeleton']>
export const LazySidebarMenuSub: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarMenuSub']>
export const LazySidebarMenuSubButton: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarMenuSubButton']>
export const LazySidebarMenuSubItem: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarMenuSubItem']>
export const LazySidebarProvider: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarProvider']>
export const LazySidebarRail: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarRail']>
export const LazySidebarSeparator: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarSeparator']>
export const LazySidebarTrigger: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarTrigger']>
export const LazySkeleton: LazyComponent<typeof import("../app/components/ui/skeleton/index")['Skeleton']>
export const LazyProgress: LazyComponent<typeof import("../app/components/ui/progress/index")['Progress']>
export const LazySheet: LazyComponent<typeof import("../app/components/ui/sheet/index")['Sheet']>
export const LazySheetClose: LazyComponent<typeof import("../app/components/ui/sheet/index")['SheetClose']>
export const LazySheetContent: LazyComponent<typeof import("../app/components/ui/sheet/index")['SheetContent']>
export const LazySheetDescription: LazyComponent<typeof import("../app/components/ui/sheet/index")['SheetDescription']>
export const LazySheetFooter: LazyComponent<typeof import("../app/components/ui/sheet/index")['SheetFooter']>
export const LazySheetHeader: LazyComponent<typeof import("../app/components/ui/sheet/index")['SheetHeader']>
export const LazySheetTitle: LazyComponent<typeof import("../app/components/ui/sheet/index")['SheetTitle']>
export const LazySheetTrigger: LazyComponent<typeof import("../app/components/ui/sheet/index")['SheetTrigger']>
export const LazySpinner: LazyComponent<typeof import("../app/components/ui/spinner/index")['Spinner']>
export const LazyToaster: LazyComponent<typeof import("../app/components/ui/sonner/index")['Toaster']>
export const LazyRangeCalendar: LazyComponent<typeof import("../app/components/ui/range-calendar/index")['RangeCalendar']>
export const LazyRangeCalendarCell: LazyComponent<typeof import("../app/components/ui/range-calendar/index")['RangeCalendarCell']>
export const LazyRangeCalendarCellTrigger: LazyComponent<typeof import("../app/components/ui/range-calendar/index")['RangeCalendarCellTrigger']>
export const LazyRangeCalendarGrid: LazyComponent<typeof import("../app/components/ui/range-calendar/index")['RangeCalendarGrid']>
export const LazyRangeCalendarGridBody: LazyComponent<typeof import("../app/components/ui/range-calendar/index")['RangeCalendarGridBody']>
export const LazyRangeCalendarGridHead: LazyComponent<typeof import("../app/components/ui/range-calendar/index")['RangeCalendarGridHead']>
export const LazyRangeCalendarGridRow: LazyComponent<typeof import("../app/components/ui/range-calendar/index")['RangeCalendarGridRow']>
export const LazyRangeCalendarHeadCell: LazyComponent<typeof import("../app/components/ui/range-calendar/index")['RangeCalendarHeadCell']>
export const LazyRangeCalendarHeader: LazyComponent<typeof import("../app/components/ui/range-calendar/index")['RangeCalendarHeader']>
export const LazyRangeCalendarHeading: LazyComponent<typeof import("../app/components/ui/range-calendar/index")['RangeCalendarHeading']>
export const LazyRangeCalendarNextButton: LazyComponent<typeof import("../app/components/ui/range-calendar/index")['RangeCalendarNextButton']>
export const LazyRangeCalendarPrevButton: LazyComponent<typeof import("../app/components/ui/range-calendar/index")['RangeCalendarPrevButton']>
export const LazySlider: LazyComponent<typeof import("../app/components/ui/slider/index")['Slider']>
export const LazyStepper: LazyComponent<typeof import("../app/components/ui/stepper/index")['Stepper']>
export const LazyStepperDescription: LazyComponent<typeof import("../app/components/ui/stepper/index")['StepperDescription']>
export const LazyStepperIndicator: LazyComponent<typeof import("../app/components/ui/stepper/index")['StepperIndicator']>
export const LazyStepperItem: LazyComponent<typeof import("../app/components/ui/stepper/index")['StepperItem']>
export const LazyStepperSeparator: LazyComponent<typeof import("../app/components/ui/stepper/index")['StepperSeparator']>
export const LazyStepperTitle: LazyComponent<typeof import("../app/components/ui/stepper/index")['StepperTitle']>
export const LazyStepperTrigger: LazyComponent<typeof import("../app/components/ui/stepper/index")['StepperTrigger']>
export const LazyTable: LazyComponent<typeof import("../app/components/ui/table/index")['Table']>
export const LazyTableBody: LazyComponent<typeof import("../app/components/ui/table/index")['TableBody']>
export const LazyTableCaption: LazyComponent<typeof import("../app/components/ui/table/index")['TableCaption']>
export const LazyTableCell: LazyComponent<typeof import("../app/components/ui/table/index")['TableCell']>
export const LazyTableEmpty: LazyComponent<typeof import("../app/components/ui/table/index")['TableEmpty']>
export const LazyTableFooter: LazyComponent<typeof import("../app/components/ui/table/index")['TableFooter']>
export const LazyTableHead: LazyComponent<typeof import("../app/components/ui/table/index")['TableHead']>
export const LazyTableHeader: LazyComponent<typeof import("../app/components/ui/table/index")['TableHeader']>
export const LazyTableRow: LazyComponent<typeof import("../app/components/ui/table/index")['TableRow']>
export const LazySwitch: LazyComponent<typeof import("../app/components/ui/switch/index")['Switch']>
export const LazyTextarea: LazyComponent<typeof import("../app/components/ui/textarea/index")['Textarea']>
export const LazyTabs: LazyComponent<typeof import("../app/components/ui/tabs/index")['Tabs']>
export const LazyTabsContent: LazyComponent<typeof import("../app/components/ui/tabs/index")['TabsContent']>
export const LazyTabsList: LazyComponent<typeof import("../app/components/ui/tabs/index")['TabsList']>
export const LazyTabsTrigger: LazyComponent<typeof import("../app/components/ui/tabs/index")['TabsTrigger']>
export const LazyToggle: LazyComponent<typeof import("../app/components/ui/toggle/index")['Toggle']>
export const LazyTagsInput: LazyComponent<typeof import("../app/components/ui/tags-input/index")['TagsInput']>
export const LazyTagsInputInput: LazyComponent<typeof import("../app/components/ui/tags-input/index")['TagsInputInput']>
export const LazyTagsInputItem: LazyComponent<typeof import("../app/components/ui/tags-input/index")['TagsInputItem']>
export const LazyTagsInputItemDelete: LazyComponent<typeof import("../app/components/ui/tags-input/index")['TagsInputItemDelete']>
export const LazyTagsInputItemText: LazyComponent<typeof import("../app/components/ui/tags-input/index")['TagsInputItemText']>
export const LazyTooltip: LazyComponent<typeof import("../app/components/ui/tooltip/index")['Tooltip']>
export const LazyTooltipContent: LazyComponent<typeof import("../app/components/ui/tooltip/index")['TooltipContent']>
export const LazyTooltipProvider: LazyComponent<typeof import("../app/components/ui/tooltip/index")['TooltipProvider']>
export const LazyTooltipTrigger: LazyComponent<typeof import("../app/components/ui/tooltip/index")['TooltipTrigger']>
export const LazyToggleGroup: LazyComponent<typeof import("../app/components/ui/toggle-group/index")['ToggleGroup']>
export const LazyToggleGroupItem: LazyComponent<typeof import("../app/components/ui/toggle-group/index")['ToggleGroupItem']>
export const LazyIcon: LazyComponent<typeof import("../node_modules/@nuxt/icon/dist/runtime/components/index")['default']>
export const LazyNuxtPage: LazyComponent<typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']>
export const LazyNoScript: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']>
export const LazyLink: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']>
export const LazyBase: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']>
export const LazyTitle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']>
export const LazyMeta: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']>
export const LazyStyle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']>
export const LazyHead: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']>
export const LazyHtml: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']>
export const LazyBody: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']>
export const LazyNuxtIsland: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']>

export const componentNames: string[]
